permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ["CNAME", "README.md"]

title: Kuudes mauste
tagline: I see hungry people

disqus:
  shortname: kuudesmauste

categorypages:
- name: Reseptit
  url: /luokka/ruuanlaitto/reseptit/
- name: Välineet
  url: /luokka/ruuanlaitto/valineet/
- name: Ruuanlaitto
  url: /luokka/ruuanlaitto/
- name: Viinit
  url: /luokka/viinit/
- name: Kuudes mauste
  url: /luokka/blogi/
